Do branch
RoboTeamTwente/roboteam_microcontroller3.0 pull request #2
Opened 2018-11-09 13:17 UTC by kJh19

Made the velocity control file.
and created the structs necessary in other control files and put them in a utils header.

2018-11-13 16:05 UTC, casdoorn requested changes

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +// Basically set constants
give these constants a better name, they are not very descriptive. This especially holds for c and s

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +//function to prevent asking for impossible stuff
What??? Just say it scales and limits the outgoing wheel velocities.

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +
I assume these PID constants will get values?

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +	float globalXVel = input[body_x];//cos(input[1])*input[0];
What are these comments?

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +		for (int i = 0; i<2; ++i){
this will only run once with i = 1, the other value is skipped (i assume you want to index from 0 to 1). Change ++i to i++ and it works

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +static void doublePID(float PIDvalue[2], float ref[2], float state[3], struct PIDconstants K){
make a generic PID function and call it twice, it will make it more readable and more modular

2018-11-13 16:05 UTC, casdoorn commented on Src/vel_control.c
> +		float P[2] = {0};
no need to make these arrays, as both are only used once in every for loop, so create them in the for loop.

2018-11-14 08:20 UTC, kJh19 commented on Src/vel_control.c
> +// Basically set constants
Renamed them

2018-11-14 08:20 UTC, kJh19 commented on Src/vel_control.c
> +//function to prevent asking for impossible stuff
Done

2018-11-14 08:20 UTC, kJh19 commented on Src/vel_control.c
> +
Added TODO

2018-11-14 08:20 UTC, kJh19 commented on Src/vel_control.c
> +	float globalXVel = input[body_x];//cos(input[1])*input[0];
Removed them

2018-11-14 08:20 UTC, kJh19 commented on Src/vel_control.c
> +		for (int i = 0; i<2; ++i){
Removed it

2018-11-14 08:20 UTC, kJh19 commented on Src/vel_control.c
> +static void doublePID(float PIDvalue[2], float ref[2], float state[3], struct PIDconstants K){
Done

2018-11-14 08:21 UTC, kJh19 commented on Src/vel_control.c
> +		float P[2] = {0};
Removed it

2018-11-14 14:05 UTC, casdoorn commented on Src/vel_control.c
>  	static float prev_e = 0;
put prev_e in the struct, that way it is not shared

2018-11-14 14:05 UTC, casdoorn commented on Src/vel_control.c
>  	I += K.kI*err*TIME_DIFF;
TIME_DIFF needs to be passed as a reference, as it will not always be the same for every PID. Either put it in the struct, or use the actual time difference between calculations and pass that as a reference.

2018-11-14 15:16 UTC, merged