Feature/wheel control
RoboTeamTwente/roboteam_microcontroller3.0 pull request #9
Opened 2018-12-07 12:49 UTC by kJh19

Added wheel control file, also fixed some bugs in the velocity control that i realised in the model, and added angular velocity control

2018-12-18 15:04 UTC, casdoorn requested changes

2018-12-18 15:04 UTC, casdoorn commented on Src/vel_control.c
> +	//TODO check minuses
separate the common calculations in one single calculation

2018-12-18 15:04 UTC, casdoorn commented on Src/vel_control.c
> +static void global2Local(float global[3], float local[3], float  yaw){
make a cos and sin lookup table, to save calculations

2018-12-18 15:04 UTC, casdoorn commented on Src/wheels.c
> +	//Scale
calculate the K once and move it out of this function for readability

2018-12-18 15:04 UTC, casdoorn commented on Src/wheels.c
> +	//Limit
if output is between -1.0f and 1.0f nothing changes as the output is not copied to pwm, so it will almost never turn off

2018-12-18 15:04 UTC, casdoorn commented on Src/wheels.c
> +
being nitpicky: remove aditional tabs

2018-12-18 15:04 UTC, casdoorn commented on Inc/Utils/control_util.h
> +	float PIDvalue = P + K->I - D;
add TODO for checking +/- sign

2018-12-19 14:00 UTC, kJh19 commented on Src/vel_control.c
> +	//TODO check minuses
done

2018-12-19 14:01 UTC, kJh19 commented on Src/vel_control.c
> +static void global2Local(float global[3], float local[3], float  yaw){
will do this when proven necesarry

2018-12-19 14:07 UTC, kJh19 commented on Src/wheels.c
> +	//Scale
now a global variable

2018-12-19 14:09 UTC, kJh19 commented on Src/wheels.c
> +	//Limit
added an else that turns all the remains into zero

2018-12-19 14:10 UTC, kJh19 commented on Src/wheels.c
> +
What tabs?

2018-12-19 14:19 UTC, kJh19 commented on Inc/Utils/control_util.h
> +	float PIDvalue = P + K->I - D;
it's plus

2018-12-20 12:35 UTC, casdoorn approved these changes

2018-12-20 12:35 UTC, merged